services:
  # --- NGINX GATEWAY & SSL ---
  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/var/www/html:ro
      - /mnt/data/minio/data:/var/www/video:ro
      - ./nginx-gateway/certbot/www:/var/www/certbot:ro
      - ./nginx-gateway/certbot/conf:/etc/letsencrypt:ro
    networks:
      - octane-net
    depends_on:
      - grafana
      - kibana
      - kafka-ui
      - dozzle
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx-gateway/certbot/www:/var/www/certbot:rw
      - ./nginx-gateway/certbot/conf:/etc/letsencrypt:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # --- STREAMING ENGINE ---
  rtmp-ingest:
    image: tiangolo/nginx-rtmp:latest
    container_name: live-ingest
    restart: always
    ports:
      - "1935:1935" # Standard RTMP Port (Mapped 1:1)
    volumes:
      - /mnt/data/minio/data:/minio_data:rw
      - ./services/rtmp.conf:/etc/nginx/nginx.conf:ro
      - ./services/stat.xsl:/usr/share/nginx/html/stat.xsl:ro
    networks:
      - octane-net
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G

  ffmpeg:
    image: linuxserver/ffmpeg:latest
    container_name: ffmpeg-worker
    user: "1001:1001"
    volumes:
      - /mnt/data/minio/data:/minio_data:rw
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    restart: always
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 12G

  # --- KAFKA ECOSYSTEM ---
  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION}
    container_name: kafka
    ports:
      - "8084:8084"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:8084'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://broker.octanebrew.dev:8084'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - ${KAFKA_DATA_DIR}:/var/lib/kafka/data
    networks:
      - octane-net

  connect:
    image: confluentinc/cp-kafka-connect:${CONFLUENT_VERSION}
    container_name: connect
    depends_on:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
    volumes:
      - /mnt/data/connect/plugins:/usr/share/confluent-hub-components
    networks:
      - octane-net

  kafka-ui:
    image: kafbat/kafka-ui:${KAFBAT_VERSION}
    container_name: kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'OpenStream-Cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      AUTH_TYPE: 'LOGIN_FORM'
      SPRING_SECURITY_USER_NAME: ${KAFKA_UI_USER}
      SPRING_SECURITY_USER_PASSWORD: ${KAFKA_UI_PASS}
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: 'OpenStream-Connect'
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: 'http://connect:8083'
    depends_on:
      - kafka
      - connect
    networks:
      - octane-net

  # --- DATA STORES ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - node.name=es01
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - ${ELASTIC_DATA_DIR}:/usr/share/elasticsearch/data
    networks:
      - octane-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "27017:27017" 
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
    restart: always
    networks:
      - octane-net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_DATA_DIR}:/data
    command: server /data --console-address ":9001"
    networks:
      - octane-net

  # --- OBSERVABILITY ---
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - SERVER_PUBLICBASEURL=https://kibana.octanebrew.dev
      - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch
    networks:
      - octane-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=grafana.octanebrew.dev
      - GF_SERVER_ROOT_URL=https://grafana.octanebrew.dev
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    volumes:
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - octane-net

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - octane-net

  # --- DATA EXPORTERS ---
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - octane-net

  mongodb-exporter:
    image: percona/mongodb_exporter:0.47.2
    container_name: mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/admin?authSource=admin
    command: ['--collect-all', '--compatible-mode']
    depends_on: [mongodb]
    networks:
      - octane-net

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    command: ["--kafka.server=kafka:9092", "--kafka.version=3.7.0"]
    depends_on: [kafka]
    networks:
      - octane-net

  elasticsearch-exporter:
    image: prometheuscommunity/elasticsearch-exporter:latest
    container_name: elasticsearch-exporter
    command:
      - '--es.uri=${ES_EXPORTER_URI}'
      - '--es.all'
      - '--es.indices'
      - '--es.ssl-skip-verify'
    depends_on: [elasticsearch]
    networks:
      - octane-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ${PROMETHEUS_CONFIG_DIR}:/etc/prometheus
      - ${PROMETHEUS_DATA_DIR}:/prometheus
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    depends_on:
      - node-exporter
      - mongodb-exporter
      - kafka-exporter
      - elasticsearch-exporter
    networks:
      - octane-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - octane-net

networks:
  octane-net:
    name: octane-net
    driver: bridge